apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: main-zone
  namespace: anthology-ai
spec:
  description: "DNS zone for 2100.cool"
  dnsName: 2100.cool.
  visibility: public
  dnssecConfig:
    state: on
