apiVersion: cloud.google.com/v1
kind: BackendService
metadata:
  name: lb-ip-2100-cool-backend
  namespace: anthology-ai
spec:
  loadBalancingScheme: EXTERNAL
  protocol: HTTP
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 60
  ipVersion: IPV4_ONLY
  enableCDN: true
  sessionAffinity: CLIENT_IP
  healthChecks:
    - name: tcp-443-health-check
      config:
        type: TCP
        port: 443
        checkIntervalSec: 5
        timeoutSec: 5
        unhealthyThreshold: 2
        healthyThreshold: 2
  customRequestHeaders:
    - "X-Content-Type-Options: nosniff"
    - "X-Frame-Options: DENY"
  backend:
    - balancingMode: UTILIZATION
      group: ${NEG_GROUP}
  securitySettings:
    securityPolicyRef:
      name: anthology-security-policy
  failoverPolicy:
    disableConnectionDrainOnFailover: false
    dropTrafficIfUnhealthy: true
    failoverRatio: 0.1
---
apiVersion: monitoring.googleapis.com/v1
kind: AlertPolicy
metadata:
  name: backend-monitoring
  namespace: anthology-ai
spec:
  displayName: "Backend Service Monitoring"
  conditions:
    - displayName: "Backend Error Rate"
      conditionThreshold:
        filter: metric.type="loadbalancing.googleapis.com/https/backend_request_count" 
        comparison: COMPARISON_GT
        threshold: 0.01
        duration: 300s