name: integration-gateway-16-agent-global
description: Global load balancer for 16-Agent Personality System with bullet balancing
protocol: HTTPS
port: 443
portName: https
timeoutSec: 300
connectionDraining:
  drainingTimeoutSec: 300
sessionAffinity: CLIENT_IP
affinityCookieTtlSec: 3600
loadBalancingScheme: EXTERNAL_MANAGED
backends:
  - group: regions/us-west1/networkEndpointGroups/16-agent-neg-us-west1
    balancingMode: UTILIZATION
    maxUtilization: 0.8
    capacityScaler: 1.0
  - group: regions/us-central1/networkEndpointGroups/16-agent-neg-us-central1
    balancingMode: UTILIZATION
    maxUtilization: 0.8
    capacityScaler: 1.0
  - group: regions/europe-west1/networkEndpointGroups/16-agent-neg-europe-west1
    balancingMode: UTILIZATION
    maxUtilization: 0.8
    capacityScaler: 1.0
healthChecks:
  - 16-agent-health-check
customRequestHeaders:
  - "X-Agent-System-Version: v1.0"
  - "X-Load-Balancer: 16-agent-global"
