name = "asoos-2100-cool"
main = "cloudflare-pages-deployment/index-full.js"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "production"

routes = [
  { pattern = "asoos.2100.cool/*", zone_name = "2100.cool" }
]
