name = "asoos-2100-cool-worker-production"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "aef30d920913c188b9b6048cc7f42951"

# Professional ASOOS.2100.Cool Landing Page
# 1,699-line professional page with 20M+ AI agents
# Full team showcase, comprehensive features

[vars]
ENVIRONMENT = "production"
SECURITY_LEVEL = "diamond_sao"
SITE_DOMAIN = "asoos.2100.cool"
SERVICE_NAME = "ASOOS Professional Landing Page"
VERSION = "1.0.0"
AGENTS_COUNT = "20000000"

# Production Routes for asoos.2100.cool
[[routes]]
pattern = "asoos.2100.cool/*"
zone_name = "2100.cool"

[[routes]]
pattern = "asoos.2100.cool"
zone_name = "2100.cool"

[build]
command = ""
cwd = ""
watch_dir = ""

# Production Environment Configuration
[env.production]
name = "asoos-2100-cool-worker-production"
routes = [
  { pattern = "asoos.2100.cool/*", zone_name = "2100.cool" },
  { pattern = "asoos.2100.cool", zone_name = "2100.cool" }
]

[env.production.vars]
ENVIRONMENT = "production"
SECURITY_LEVEL = "diamond_sao"
SITE_DOMAIN = "asoos.2100.cool"
SERVICE_NAME = "ASOOS Professional Landing Page"
VERSION = "1.0.0"
AGENTS_COUNT = "20000000"

# Security and performance settings
[placement]
mode = "smart"
