name = "wfa-production-orchestration"
main = "production-wfa-orchestration.js"
compatibility_date = "2025-08-27"

# Production environment configuration
[env.production]
name = "wfa-production-orchestration"
route = { pattern = "asoos.2100.cool/wfa/*", zone_name = "2100.cool" }

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"
WFA_AGENTS = "20000000"
WFA_SECTORS = "200"
WFA_JOB_CLUSTERS = "64000000"
WFA_CAREER_CLUSTERS = "319998"
VICTORY36_ENABLED = "true"

# KV Namespaces for agent state management
[[env.production.kv_namespaces]]
binding = "WFA_STATE"
id = "wfa-agent-state-prod"
preview_id = "wfa-agent-state-preview"

[[env.production.kv_namespaces]]
binding = "CAREER_CLUSTERS_KV"
id = "wfa-career-clusters-prod"
preview_id = "wfa-career-clusters-preview"

[[env.production.kv_namespaces]]
binding = "JOB_CLUSTERS_KV"
id = "wfa-job-clusters-prod"
preview_id = "wfa-job-clusters-preview"

[[env.production.kv_namespaces]]
binding = "SECTOR_MAPPINGS"
id = "wfa-sector-mappings-prod"
preview_id = "wfa-sector-mappings-preview"

# Durable Objects for swarm coordination
[[env.production.durable_objects.bindings]]
name = "SWARM_COORDINATOR"
class_name = "SwarmCoordinator"

[[env.production.durable_objects.bindings]]
name = "VICTORY36_PROTECTION"
class_name = "Victory36Protection"

[[env.production.durable_objects.bindings]]
name = "MCP_DNS_MANAGER"
class_name = "MCPDNSManager"

# R2 Bucket for large data storage
[[env.production.r2_buckets]]
binding = "WFA_ARTIFACTS"
bucket_name = "wfa-production-artifacts"

# Service bindings for microservices architecture
[[env.production.services]]
binding = "AGENT_REGISTRY"
service = "wfa-agent-registry"
environment = "production"

[[env.production.services]]
binding = "CLUSTER_MANAGER"
service = "wfa-cluster-manager"
environment = "production"

[[env.production.services]]
binding = "DNS_AUTOMATION"
service = "wfa-dns-automation"
environment = "production"

# Analytics engine for monitoring
[[env.production.analytics_engine_datasets]]
binding = "WFA_METRICS"
dataset = "wfa_production_metrics"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["SwarmCoordinator", "Victory36Protection", "MCPDNSManager"]
