name = "mcp-dynamic-proxy"
main = "mcp-proxy-worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
TOTAL_AGENTS = "20000000"

routes = [
  { pattern = "mcp.aipub.2100.cool/*", zone_name = "2100.cool" },
  { pattern = "mcp.*.2100.cool/*", zone_name = "2100.cool" }
]

[placement]
mode = "smart"
