apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-gravity-gateway
  namespace: aixtiv-mocoa
  labels:
    app: anti-gravity
    component: integration-gateway
    tier: orchestration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anti-gravity
  template:
    metadata:
      labels:
        app: anti-gravity
        component: integration-gateway
        tier: orchestration
    spec:
      containers:
      - name: anti-gravity-gateway
        image: gcr.io/api-for-warp-drive/integration-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: DR_LUCY_ENDPOINT
          value: "http://dr-lucy-service.aixtiv-mocorix:8080"
        - name: DREAM_COMMANDER_ENDPOINT
          value: "http://dream-commander-service.aixtiv-mocorix:8080"
        - name: VICTORY36_ENDPOINT
          value: "http://victory36-time-presser-service.aixtiv-mocorix2:8080"
        - name: SYSTEM_TYPE
          value: "anti-gravity"
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_NAME
          value: "anti-gravity-gateway"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "2Gi"
            cpu: "1"
            ephemeral-storage: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: anti-gravity-gateway-service
  namespace: aixtiv-mocoa
spec:
  selector:
    app: anti-gravity
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP