openapi: 3.0.0
info:
  title: AIXTIV Orchestra API
  version: 1.0.0
  description: API for managing AI agents and deployments

paths:
  /agents:
    post:
      summary: Create a new agent
      tags: [Agents]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentCreate'
      responses:
        201:
          description: Agent created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
    
    get:
      summary: List all agents
      tags: [Agents]
      security:
        - BearerAuth: []
      responses:
        200:
          description: List of agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'

components:
  schemas:
    Agent:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [core, deploy, engage]
        status:
          type: string
          enum: [starting, running, stopped, error]
        config:
          $ref: '#/components/schemas/AgentConfig'
        metrics:
          $ref: '#/components/schemas/AgentMetrics'
  
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

