certificateRotation:
  schedule: "45d"
  overlap: "7d"
  validation: true
  rollback: true
  monitoring: true
  alerts:
    enabled: true
    channels: ["slack", "email"]
    events: ["start", "complete", "fail"]