# WFA PRODUCTION SWARM - SIMPLIFIED CLOUD BUILD
# Cloud-to-Cloud deployment for 20M agents across 200 sectors
# Commander: Phillip Corey Roark

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/wfa-production-swarm:latest'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/wfa-production-swarm:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'wfa-production-swarm'
      - '--image=gcr.io/$PROJECT_ID/wfa-production-swarm:latest'
      - '--platform=managed'
      - '--region=us-west1'
      - '--allow-unauthenticated'
      - '--memory=8Gi'
      - '--cpu=4'
      - '--concurrency=1000'
      - '--min-instances=5'
      - '--max-instances=100'
      - '--timeout=3600'
      - '--service-account=wfa-production@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=NODE_ENV=production,WFA_AGENTS_COUNT=20000000,WFA_SECTORS_COUNT=200,JOB_CLUSTERS_COUNT=64000000,CAREER_CLUSTERS_COUNT=319998,VICTORY36_PROTECTION=maximum,CLOUD_TO_CLOUD_MODE=true,MCP_DNS_AUTOMATION=enabled'
      - '--set-secrets=MONGODB_CONNECTION_STRING=mongodb-atlas-connection:latest,CLOUDFLARE_API_TOKEN=cloudflare-api-token:latest,CLOUDFLARE_ZONE_ID=cloudflare-zone-id:latest'
      - '--quiet'

  # Step 4: Display deployment info
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🚀 WFA Production Swarm deployed successfully!"
        echo "🌐 Cloud Run Service URL: https://wfa-production-swarm-859242575175.a.run.app"
        echo "🔗 Cloudflare Workers: https://asoos.2100.cool/wfa/"
        echo "👨‍💼 Commander: Phillip Corey Roark"
        echo "📊 Managing 20M agents across 200 sectors"
        echo "🛡️  Victory36 Protection: MAXIMUM"
        echo "⚡ Cloud-to-Cloud Mode: ENABLED"

# Cloud Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

# Build timeout (15 minutes)
timeout: '900s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/wfa-production-swarm:latest'

# Tags for build identification
tags:
  - 'wfa-production-swarm'
  - 'victory36-protection'
  - 'cloud-to-cloud'
