name = "asoos-main-site-mcp"
main = "asoos-production-worker.js"
compatibility_date = "2025-08-27"

[env.production]
name = "asoos-main-site-mcp"

[[env.production.routes]]
pattern = "asoos.2100.cool/*"
zone_name = "2100.cool"

[[env.production.routes]]
pattern = "mcp.aipub.2100.cool/*"
zone_name = "2100.cool"

[vars]
ENVIRONMENT = "production"
MCP_TARGET = "https://mocoa-owner-interface-859242575175.us-west1.run.app"
