
# visionlake_cloudbuild.yaml (corrected for MCP region)

steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'

  # Step 2: Optional test step
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: 'functions'

  # Step 3: Deploy to US-WEST1-C (MCP for RIX, QRICs, CRX, Super Agents)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy agentPulsePanel         --runtime nodejs20         --trigger-http         --allow-unauthenticated         --region=us-west1         --source=functions         --entry-point=agentPulseHandler         --project=visionlake-core-mcp

  # Step 4: Log the deployment to GCP logs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "MCP Deployment complete for agentPulsePanel in us-west1-c" | gcloud logging write agent-deployments

timeout: 900s

tags:
  - aixtiv
  - visionlake
  - mcp
  - superagents
  - crx
  - rix
  - qric
