#!/bin/bash
# Node.js Version Monitoring Cron Job
# Runs daily to check Node.js version status
# Generated by Node.js Self-Monitoring System

cd "/Users/as/asoos/integration-gateway"
node scripts/node-version-monitor.js --cron-mode

# Check exit code and send alerts if needed
if [ $? -ne 0 ]; then
    echo "Node.js version check failed - alerts sent" | logger -t node-version-monitor
fi
