aiConfig:
  claude:
    model: "claude-3-5-sonnet-20241022"
    maxTokens: 200000
    temperature: 0.7
    enabled: true
    monitoring: true
    
  vertex:
    project: "warp-drive-ai"
    location: "us-central1"
    model: "vertex-large"
    enabled: true
    monitoring: true
    
orchestration:
  autoScaling: true
  loadBalancing: true
  fallback: true
  monitoring:
    enabled: true
    alerts: true
    metrics: ["latency", "usage", "errors"]