automation:
  tasks:
    - name: "data-processing"
      language: "python"
      code: |
        import pandas as pd
        import numpy as np
        
        def process_data(data):
            df = pd.DataFrame(data)
            return df.describe()
            
    - name: "api-request"
      language: "javascript"
      code: |
        async function fetchData(url) {
          const response = await fetch(url);
          return response.json();
        }
        
    - name: "system-check"
      language: "shell"
      code: |
        #!/bin/bash
        echo "Running system check..."
        df -h
        free -m
        top -b -n 1

execution:
  parallel: true
  logging: true
  retry: 3