apiVersion: v1
kind: Service
metadata:
  name: super-claude-staging-backend
  namespace: anthology-ai-staging
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: super-claude-ui-staging