runtime: nodejs22  # Will upgrade to nodejs24 when available on App Engine
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GOOGLE_CLOUD_PROJECT: "api-for-warp-drive"
  ASOOS_FLYER_VERSION: "2.0.0-ml-enhanced"
  ML_PIPELINE_ENABLED: "true"
  FEEDBACK_LOOP_ACTIVE: "true"

handlers:
- url: /.*
  script: auto
  
entrypoint: node server-cloud.js
