# Enhanced ASOOS Diamond SAO Interface - Cloud Build Configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/diamond-sao-interface:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/diamond-sao-interface:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/diamond-sao-interface:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/diamond-sao-interface:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'diamond-sao-interface'
      - '--image'
      - 'gcr.io/$PROJECT_ID/diamond-sao-interface:$BUILD_ID'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '100'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/diamond-sao-interface:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/diamond-sao-interface:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'