name: Deploy All Agents

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-lucy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'lucy-auto@api-for-warp-drive.iam.gserviceaccount.com'
      
      - uses: google-github-actions/setup-gcloud@v1
      
      - name: Deploy Lucy Auto
        run: |
          gcloud run deploy lucy-webhook \
            --source=. \
            --region=us-west1 \
            --platform=managed \
            --allow-unauthenticated
          
      - name: Health Check Lucy
        run: |
          sleep 30
          curl -f $(gcloud run services describe lucy-webhook \
            --region=us-west1 \
            --format='value(status.url)')/health || exit 1

  deploy-claude:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'super-claude-1@api-for-warp-drive.iam.gserviceaccount.com'
      
      - uses: google-github-actions/setup-gcloud@v1
      
      - name: Deploy Super Claude
        run: |
          gcloud run deploy super-claude-1 \
            --source=. \
            --region=us-west4 \
            --platform=managed \
            --allow-unauthenticated
      
      - name: Health Check Claude
        run: |
          sleep 30
          curl -f $(gcloud run services describe super-claude-1 \
            --region=us-west4 \
            --format='value(status.url)')/health || exit 1

  update-status:
    needs: [deploy-lucy, deploy-claude]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Status
        if: success()
        run: |
          jq '.agents[] |= if .name == "lucy-auto" or .name == "super-claude-1" then .status = "DEPLOYED" else . end' \
            config/agents.json > temp.json && mv temp.json config/agents.json
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update agent deployment status [skip ci]"
          git push