name: Aixtiv CLI Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-west1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Google Cloud Authentication
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: 'github-actions-deploy@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com'
        create_credentials_file: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Run linting
      run: npm run lint || echo "No linting configured"

    - name: Run tests
      run: npm test || echo "No tests configured"

    - name: Build application
      run: npm run build || echo "No build script configured"

    - name: Build Docker image
      run: |
        echo "Building Docker image for aixtiv-cli"
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/aixtiv-cli:$COMMIT_SHA .
        docker tag gcr.io/${{ secrets.GCP_PROJECT }}/aixtiv-cli:$COMMIT_SHA gcr.io/${{ secrets.GCP_PROJECT }}/aixtiv-cli:latest

    - name: Configure Docker authentication for GCR
      run: |
        gcloud auth configure-docker gcr.io

    - name: Push Docker image to GCR
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/aixtiv-cli:$COMMIT_SHA
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/aixtiv-cli:latest

    - name: Deploy to Cloud Run
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        gcloud run deploy aixtiv-cli \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/aixtiv-cli:$COMMIT_SHA \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT }}

    - name: Post Deployment Summary
      run: |
        echo "### Aixtiv CLI Build and Deployment Completed ✅" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Successfully built and deployed aixtiv-cli to Cloud Run" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Deployment Information:**" >> $GITHUB_STEP_SUMMARY
        echo "- Region: ${{ env.REGION }}" >> $GITHUB_STEP_SUMMARY
        echo "- Project: ${{ secrets.GCP_PROJECT }}" >> $GITHUB_STEP_SUMMARY
        echo "- Service: aixtiv-cli" >> $GITHUB_STEP_SUMMARY
        echo "- Timestamp: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY

