name: Deploy Super Claude 1

on:
  push:
    paths:
      - 'agents/super-claude/**'
      - 'config/job-spec-claude.json'
  workflow_dispatch:

env:
  PROJECT_ID: api-for-warp-drive
  REGION: us-west4
  ZONE: us-west4-c
  AGENT_NAME: super-claude-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{ env.AGENT_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
      
      - uses: google-github-actions/setup-gcloud@v1
      
      - name: Deploy Agent
        run: |
          gcloud ai agents update ${{ env.AGENT_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --location=${{ env.REGION }} \
            --config=config/job-spec-claude.json

      - name: Update Status
        run: |
          jq '.agents[] |= if .name == "${{ env.AGENT_NAME }}" then .status = "DEPLOYED" else . end' config/agents.json > temp.json
          mv temp.json config/agents.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config/agents.json
          git commit -m "Update Super Claude 1 agent status"
          git push