name = "wfa-orchestration-worker"
main = "worker.js"
compatibility_date = "2025-01-02"
compatibility_flags = ["nodejs_compat"]
account_id = "aef30d920913c188b9b6048cc7f42951"

# Development environment
[vars]
ENVIRONMENT = "development"
MCP_DOMAIN = "mcp.aipub.2100.cool"
MASTER_MCP_SERVER = "mcp.asoos.2100.cool"
AGENT_CAPACITY = "1000000"
SECTORS = "10"
CLOUD_ML_REGION = "us-west1"
GCP_PROJECT = "api-for-warp-drive"
DNS_MODE = "automated"
HEALING_MODE = "enabled"

# Development limits
[limits]
cpu_ms = 10000
memory = 256
