apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coaching2100-comprehensive-policy
  namespace: anthology-ai
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector: {}
      - namespaceSelector:
          matchLabels:
            organization: coaching2100
      ports:
        - protocol: TCP
        - protocol: UDP
  egress:
    - to:
      - podSelector: {}
      - namespaceSelector:
          matchLabels:
            organization: coaching2100
    - ports:
        - port: 53
          protocol: UDP
        - port: 443
          protocol: TCP