steps:
# Build the container image with AMD64 platform using Kaniko
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - '--destination=gcr.io/PROJECT_ID/mocoa-cloud-run:${BUILD_ID}'
  - '--destination=gcr.io/PROJECT_ID/mocoa-cloud-run:latest'
  - '--context=.'
  - '--dockerfile=Dockerfile'
  - '--build-arg=BUILDKIT_INLINE_CACHE=1'
  - '--customPlatform=linux/amd64'
  - '--cache=true'
  - '--cache-ttl=24h'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'mocoa-cloud-run'
  - '--image=gcr.io/PROJECT_ID/mocoa-cloud-run:latest'
  - '--region=us-west1'
  - '--platform=managed'
  - '--allow-unauthenticated'

substitutions:
  _REGION: us-west1
  _SERVICE_NAME: mocoa-cloud-run

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  
timeout: '1200s'
