steps:
# Build step
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install']

# Deploy to App Engine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml', '--quiet', '--project=${PROJECT_ID}']

# Set environment variables
substitutions:
  _SERVICE_NAME: mocoa-cloud-run
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1200s
