stagingAutomation:
  deployment:
    automated: true
    frequency: "continuous"
    validation:
      preDeployment: true
      postDeployment: true
  
  monitoring:
    uptime:
      check: "30s"
      target: "99.99%"
    ssl:
      autoRenewal: true
      monitoring: true
    
  testing:
    automated: true
    types: ["e2e", "load", "security"]
    schedule: "continuous"
    
  recovery:
    autoHealing: true
    failover: true
    backup:
      frequency: "1h"
      retention: "7d"